package org.celllife.idart.domain.organisation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface LegalOrganisationSequence {

    Long nextValue()

}