package org.celllife.idart.domain.form

import org.celllife.idart.domain.common.Code

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class FormServiceImpl implements FormService {

    @Autowired FormRepository formRepository

    @Override
    Iterable<Form> save(Iterable<Form> forms) {
        forms.collect { form -> (save(form)) }
    }

    @Override
    Form save(Form form) {
        formRepository.save(lookupAndMerge(form))
    }

    Form lookupAndMerge(Form form) {

        Code code = getLookupCode(form)

        Form existingForm = formRepository.findOneByCode(code.system, code.value)

        if (existingForm == null) {

            // Ensure that idartCodeValue is always set
            if (form.idartCodeValue == null) {
                form.addCode(Form.IDART_SYSTEM, form.defaultCodeValue)
            }

            return form
        }

        existingForm.mergeCodes(form)
        existingForm
    }

    static Code getLookupCode(Form form) {

        if (form.idartCodeValue == null && form.defaultCodeValue == null) {
            throw new RuntimeException("No code for default system [${ Form.DEFAULT_SYSTEM}] or idart system [${ Form.IDART_SYSTEM}]")
        }

        if (form.defaultCodeValue != null) {
            return new Code(system: Form.DEFAULT_SYSTEM, value: form.defaultCodeValue)
        }

        return new Code(system: Form.IDART_SYSTEM, value: form.idartCodeValue)
    }

    @Override
    Iterable<Form> findAll() {
        formRepository.findAll()
    }

    @Override
    Form findByCode(String code) {
        formRepository.findOneByCode(Form.IDART_SYSTEM, code)
    }

    @Override
    Form findByCodes(Iterable<Code> codes) {

        if (codes == null) {
            return null
        }

        for (code in codes) {
            def form = formRepository.findOneByCode(code.system, code.value)
            if (form != null) {
                return form
            }
        }

        null
    }
}