package org.celllife.idart.domain.form

import org.celllife.idart.domain.common.Code

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface FormService {

    Iterable<Form> save(Iterable<Form> forms)

    Form save(Form form)

    Iterable<Form> findAll()

    Form findByCode(String code)

    Form findByCodes(Iterable<Code> codes)

}