package org.celllife.idart.domain.form

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface FormValidator {

    void validate(Form form) throws FormValidationException

}