package org.celllife.idart.application.product;

import org.celllife.idart.domain.product.Good;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface GoodResourceService {

    Good save(Good good);

    Good findByIdentifier(String identifier);

    Iterable<Good> findAll();

}