package org.celllife.idart.application.dispensedmedication;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface DispensedMedicationApplicationService {

}