package org.celllife.idart.application.system;

import org.celllife.idart.domain.system.System;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SystemResourceService {

    System save(System system);

    System findByIdentifier(String identifier);

    Iterable<System> findAll();

}