package org.celllife.idart.application.clinicpatient

import org.celllife.idart.application.clinic.ClinicResourceService
import org.celllife.idart.application.patient.PatientResourceService
import org.celllife.idart.domain.clinicpatient.ClinicPatientService
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.patient.Patient
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service    

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class ClinicPatientApplicationServiceImpl implements ClinicPatientResourceService {

    @Autowired ClinicResourceService clinicResourceService

    @Autowired PatientResourceService patientResourceService

    @Autowired ClinicPatientService clinicPatientService

    @Override
    void save(String clinicIdentifier, String patientIdentifier, Patient patient) {

        patient.addIdentifier(
                String.format(
                        "http://www.cell-life.org/idart/clinics/%s/patients",
                        clinicIdentifier
                ),
                patientIdentifier
        )

        save(clinicIdentifier, patient)
    }

    @Override
    void save(String clinicIdentifier, Patient patient) {

        def clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        patient = patientResourceService.save(patient)

        clinicPatientService.save(clinic, patient)
    }

    @Override
    Iterable<Patient> findPatientsByClinicIdentifier(String clinicIdentifier) {
         clinicPatientService.findPatientsByClinicIdentifier(clinicIdentifier)
    }

    @Override
    Iterable<Patient> findPatientsByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier) {
        return null
    }

    @Override
    Patient findOnePatientByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier) {
        return clinicPatientService.findPatientsByClinic()
    }
}
