package org.celllife.idart.domain.administrationmethod;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface AdministrationMethodRepository {

    AdministrationMethod save(AdministrationMethod administrationMethod)

    public <S extends AdministrationMethod> Iterable<S> save(Iterable<S> administrationMethods)

    AdministrationMethod findOne(Long pk)

    Iterable<AdministrationMethod> findAll()

    AdministrationMethod findOneByCode(String system, String code);

}
