package org.celllife.idart.domain.administrationmethod

import org.celllife.idart.domain.common.Code

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class AdministrationMethodServiceImpl implements AdministrationMethodService {

    @Autowired AdministrationMethodRepository administrationMethodRepository

    @Override
    Iterable<AdministrationMethod> save(Iterable<AdministrationMethod> administrationMethods) {
        administrationMethods.collect { administrationMethod -> (save(administrationMethod)) }
    }

    @Override
    AdministrationMethod save(AdministrationMethod administrationMethod) {
        administrationMethodRepository.save(lookupAndMerge(administrationMethod))
    }

    AdministrationMethod lookupAndMerge(AdministrationMethod administrationMethod) {

        Code code = getLookupCode(administrationMethod)

        AdministrationMethod existingAdministrationMethod = administrationMethodRepository.findOneByCode(code.system, code.value)

        if (existingAdministrationMethod == null) {

            // Ensure that idartCodeValue is always set
            if (administrationMethod.idartCodeValue == null) {
                administrationMethod.addCode(AdministrationMethod.IDART_SYSTEM, administrationMethod.defaultCodeValue)
            }

            return administrationMethod
        }

        existingAdministrationMethod.mergeCodes(administrationMethod)
        existingAdministrationMethod
    }

    static Code getLookupCode(AdministrationMethod administrationMethod) {

        if (administrationMethod.idartCodeValue == null && administrationMethod.defaultCodeValue == null) {
            throw new RuntimeException("No code for default system [${ AdministrationMethod.DEFAULT_SYSTEM}] or idart system [${ AdministrationMethod.IDART_SYSTEM}]")
        }

        if (administrationMethod.defaultCodeValue != null) {
            return new Code(system: AdministrationMethod.DEFAULT_SYSTEM, value: administrationMethod.defaultCodeValue)
        }

        return new Code(system: AdministrationMethod.IDART_SYSTEM, value: administrationMethod.idartCodeValue)
    }

    @Override
    Iterable<AdministrationMethod> findAll() {
        administrationMethodRepository.findAll()
    }

    @Override
    AdministrationMethod findByCode(String code) {
        administrationMethodRepository.findOneByCode(AdministrationMethod.IDART_SYSTEM, code)
    }

    @Override
    AdministrationMethod findByCodes(Iterable<Code> codes) {

        if (codes == null) {
            return null
        }

        for (code in codes) {
            def administrationMethod = administrationMethodRepository.findOneByCode(code.system, code.value)
            if (administrationMethod != null) {
                return administrationMethod
            }
        }

        null
    }
}