package org.celllife.idart.domain.administrationmethod

import org.celllife.idart.domain.common.Code

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface AdministrationMethodService {

    Iterable<AdministrationMethod> save(Iterable<AdministrationMethod> administrationMethods)

    AdministrationMethod save(AdministrationMethod administrationMethod)

    Iterable<AdministrationMethod> findAll()

    AdministrationMethod findByCode(String code)

    AdministrationMethod findByCodes(Iterable<Code> codes)

}