package org.celllife.idart.domain.administrationmethod

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface AdministrationMethodValidator {

    void validate(AdministrationMethod administrationMethod) throws AdministrationMethodValidationException

}