package org.celllife.idart.domain.unitofmeasure;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UnitOfMeasureRepository {

    UnitOfMeasure save(UnitOfMeasure unitOfMeasure)

    public <S extends UnitOfMeasure> Iterable<S> save(Iterable<S> unitsOfMeasure)

    UnitOfMeasure findOne(Long pk)

    Iterable<UnitOfMeasure> findAll()

    UnitOfMeasure findOneByCode(String system, String code);

}
