package org.celllife.idart.domain.unitofmeasure

import org.celllife.idart.domain.common.Code

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UnitOfMeasureService {

    Iterable<UnitOfMeasure> save(Iterable<UnitOfMeasure> unitsOfMeasure)

    UnitOfMeasure save(UnitOfMeasure unitOfMeasure)

    Iterable<UnitOfMeasure> findAll()

    UnitOfMeasure findByCode(String code)

    UnitOfMeasure findByCodes(Iterable<Code> codes)

}