package org.celllife.idart.domain.unitofmeasure

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface UnitOfMeasureValidator {

    void validate(UnitOfMeasure unitOfMeasure) throws UnitOfMeasureValidationException

}