package org.celllife.idart.domain.unitofmeasure

import org.celllife.idart.domain.common.Code

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class UnitOfMeasureServiceImpl implements UnitOfMeasureService {

    @Autowired UnitOfMeasureRepository unitOfMeasureRepository

    @Override
    Iterable<UnitOfMeasure> save(Iterable<UnitOfMeasure> unitsOfMeasure) {
        unitsOfMeasure.collect { unitOfMeasure -> (save(unitOfMeasure)) }
    }

    @Override
    UnitOfMeasure save(UnitOfMeasure unitOfMeasure) {
        unitOfMeasureRepository.save(lookupAndMerge(unitOfMeasure))
    }

    UnitOfMeasure lookupAndMerge(UnitOfMeasure unitOfMeasure) {

        Code code = getLookupCode(unitOfMeasure)

        UnitOfMeasure existingUnitOfMeasure = unitOfMeasureRepository.findOneByCode(code.system, code.value)

        if (existingUnitOfMeasure == null) {

            // Ensure that idartCodeValue is always set
            if (unitOfMeasure.idartCodeValue == null) {
                unitOfMeasure.addCode(UnitOfMeasure.IDART_SYSTEM, unitOfMeasure.defaultCodeValue)
            }

            return unitOfMeasure
        }

        existingUnitOfMeasure.mergeCodes(unitOfMeasure)
        existingUnitOfMeasure
    }

    static Code getLookupCode(UnitOfMeasure unitOfMeasure) {

        if (unitOfMeasure.idartCodeValue == null && unitOfMeasure.defaultCodeValue == null) {
            throw new RuntimeException("No code for default system [${ UnitOfMeasure.DEFAULT_SYSTEM}] or idart system [${ UnitOfMeasure.IDART_SYSTEM}]")
        }

        if (unitOfMeasure.defaultCodeValue != null) {
            return new Code(system: UnitOfMeasure.DEFAULT_SYSTEM, value: unitOfMeasure.defaultCodeValue)
        }

        return new Code(system: UnitOfMeasure.IDART_SYSTEM, value: unitOfMeasure.idartCodeValue)
    }

    @Override
    Iterable<UnitOfMeasure> findAll() {
        unitOfMeasureRepository.findAll()
    }

    @Override
    UnitOfMeasure findByCode(String code) {
        unitOfMeasureRepository.findOneByCode(UnitOfMeasure.IDART_SYSTEM, code)
    }

    @Override
    UnitOfMeasure findByCodes(Iterable<Code> codes) {

        if (codes == null) {
            return null
        }

        for (code in codes) {
            def unitOfMeasure = unitOfMeasureRepository.findOneByCode(code.system, code.value)
            if (unitOfMeasure != null) {
                return unitOfMeasure
            }
        }

        null
    }
}