package org.celllife.idart.domain.dispensation

import org.celllife.idart.domain.common.Identifier
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class DispensationServiceImpl implements DispensationService {

    @Autowired DispensationRepository dispensationRepository

    @Override
    Dispensation save(Dispensation dispensation) {

        Dispensation existingDispensation = findByIdentifiers(dispensation.identifiers)
        if (existingDispensation == null) {
            existingDispensation = dispensation.class.newInstance()
        }

        existingDispensation.merge(dispensation)

        dispensationRepository.save(existingDispensation)
    }


    @Override
    Iterable<Dispensation> findAll() {
        dispensationRepository.findAll()
    }

    @Override
    Dispensation findByIdentifier(String identifier) {
        null
    }

    @Override
    Dispensation findByIdentifiers(Iterable<Identifier> identifiers) {

        if (identifiers == null) {
            return null
        }

        for (Identifier identifier: identifiers) {
            Dispensation dispensation = dispensationRepository.findOneByIdentifier(identifier.system, identifier.value)
            if (dispensation != null) {
                return dispensation
            }
        }

        null
    }
}