package org.celllife.idart.domain.dispensation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface DispensationValidator {

    void validate(Dispensation dispensation) throws DispensationValidationException

}