package org.celllife.idart.domain.druggroup

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface DrugGroupSequence {

    Long nextValue()

}