package org.celllife.idart.domain.druggroup

import org.celllife.idart.domain.common.Identifier

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface DrugGroupService {

    DrugGroup save(DrugGroup drugGroup)

    Iterable<DrugGroup> findAll()

    DrugGroup findByIdentifier(String identifier)

    DrugGroup findByIdentifiers(Iterable<Identifier> identifiers)

}