package org.celllife.idart.application.form;

import org.celllife.idart.domain.form.Form;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface FormResourceService {

    Form save(Form form);

    Form findByCode(String code);

    Iterable<Form> findAll();

}