package org.celllife.idart.domain.person

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface PersonValidator {

    void validate(Person person) throws PersonValidationException

}