package org.celllife.idart.interfaces.service.user

import org.celllife.idart.application.user.UserResourceService
import org.celllife.idart.domain.user.User
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.*

import javax.annotation.Generated
import javax.servlet.http.HttpServletResponse

import static javax.servlet.http.HttpServletResponse.SC_CREATED

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Controller class UserResourceController {

    @Autowired UserResourceService userResourceService

    @Value('${external.base.url}') String baseUrl

    @ResponseBody
    @RequestMapping(
            value = "/users",
            method = RequestMethod.GET, produces = "application/json"
    )
    Iterable<User> findAll() {
        userResourceService.findAll()
    }

    @ResponseBody
    @RequestMapping(
            value = "/users/{username}",
            method = RequestMethod.GET, produces = "application/json"
    )
    User findByUsername(@PathVariable("username") String username) {
        userResourceService.findByUsername(username)
    }

    @RequestMapping(value = "/users", method = RequestMethod.POST)
    void save(@RequestBody User user, HttpServletResponse response) {

        user = userResourceService.save(user)

        response.setHeader("Location", "${baseUrl}/users/${user.username}")
        response.setStatus(SC_CREATED)
    }
}
