package org.celllife.idart.application.clinicdispensation;

import org.celllife.idart.domain.clinic.Clinic;
import org.celllife.idart.domain.dispensation.Dispensation;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicDispensationResourceService {

    /**
     *
     * @param clinicIdentifier
     * @param dispensationIdentifier
     * @param dispensation
     * @return
     */
    void save(String clinicIdentifier, String dispensationIdentifier, Dispensation dispensation);

    /**
     *
     * @param clinicIdentifier
     * @param dispensation
     * @return
     */
    void save(String clinicIdentifier, Dispensation dispensation);

    /**
     *
     * @param clinicIdentifier
     * @return
     */
    Iterable<Dispensation> findDispensationsByClinicIdentifier(String clinicIdentifier);

    /**
     *
     * @param clinicIdentifier
     * @param dispensationIdentifier
     * @return
     */
    Iterable<Dispensation> findDispensationsByClinicIdentifierAndDispensationIdentifier(String clinicIdentifier, String dispensationIdentifier);

    /**
     *
     * @param clinicIdentifier
     * @param dispensationIdentifier
     * @return
     */
    Dispensation findOneDispensationByClinicIdentifierAndDispensationIdentifier(String clinicIdentifier, String dispensationIdentifier);
}
