package org.celllife.idart.client.person;

import org.celllife.idart.client.common.Quantity;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-18
 * Time: 18h28
 */
public final class Height extends PhysicalCharacteristic {

    public Quantity quantity;

    public Height() {
    }
}
