package org.celllife.idart.client.person;

import java.io.Serializable;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-18
 * Time: 18h27
 */
public abstract class PhysicalCharacteristic implements Serializable {
}
