package org.celllife.idart.client.person;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-18
 * Time: 18h52
 */
public final class PostalAddress extends ContactMechanism {

    public String address1;

    public String address2;

    public String directions;

    public PostalAddress() {
    }
}
