package org.celllife.idart.infrastructure.validation.unitofmeasure

import org.celllife.idart.domain.unitofmeasure.UnitOfMeasure
import org.celllife.idart.domain.unitofmeasure.UnitOfMeasureValidationException
import org.celllife.idart.domain.unitofmeasure.UnitOfMeasureValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateUnitOfMeasureValidator implements UnitOfMeasureValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(UnitOfMeasure unitOfMeasure) throws UnitOfMeasureValidationException {

        Set<ConstraintViolation<UnitOfMeasure>> constraintViolations = validatorFactory.validator.validate(unitOfMeasure)

        if (!constraintViolations.empty) {
            throw new UnitOfMeasureValidationException(constraintViolations)
        }
    }
}
