package org.celllife.idart.application.system

import org.celllife.idart.domain.system.System
import org.celllife.idart.domain.system.SystemService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class SystemApplicationServiceImpl implements SystemApplicationService, SystemResourceService {

    @Autowired SystemService systemService

    System save(System system) {
        systemService.save(system)
    }

    System findByIdentifier(String identifier) {
        systemService.findByIdentifier(identifier)
    }

    Iterable<System> findAll() {
        systemService.findAll()
    }

}