package org.celllife.idart.application.part;

import org.celllife.idart.domain.part.Drug;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface DrugResourceService {

    Drug save(Drug drug);

    Drug findByIdentifier(String identifier);

    Iterable<Drug> findAll();

}