package org.celllife.idart.application.part;

import org.celllife.idart.domain.part.FinishedGood;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface FinishedGoodResourceService {

    FinishedGood save(FinishedGood finishedGood);

    FinishedGood findByIdentifier(String identifier);

    Iterable<FinishedGood> findAll();

}