package org.celllife.idart.application.part;

import org.celllife.idart.domain.part.Part;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface PartResourceService {

    Part save(Part part);

    Part findByIdentifier(String identifier);

    Iterable<Part> findAll();

}