package org.celllife.idart.application.part;

import org.celllife.idart.domain.part.RawMaterial;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface RawMaterialResourceService {

    RawMaterial save(RawMaterial rawMaterial);

    RawMaterial findByIdentifier(String identifier);

    Iterable<RawMaterial> findAll();

}