package org.celllife.idart.application.part;

import org.celllife.idart.domain.part.Subassembly;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SubassemblyResourceService {

    Subassembly save(Subassembly subassembly);

    Subassembly findByIdentifier(String identifier);

    Iterable<Subassembly> findAll();

}