package org.celllife.idart.application.encounter;

import org.celllife.idart.domain.encounter.Encounter;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface EncounterResourceService {

    Encounter save(Encounter encounter);

    Encounter findByIdentifier(String identifier);

    Iterable<Encounter> findAll();

}