package org.celllife.idart.client.part;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-20
 * Time: 18h17
 */
public final class EngineeringPartBillOfMaterialsItem extends PartBillOfMaterialsItem {
}
