package org.celllife.idart.client.part;

import java.util.Set;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-06-16
 * Time: 18h18
 */
public abstract class FinishedGood extends Part {

    public Set<PartBillOfMaterialsItem> billOfMaterials;

    public FinishedGood() {
    }
}
