package org.celllife.idart.client.part;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-14
 * Time: 10h44
 */
public enum PartClassificationType {

    ATC,

    REGIMEN

}