package org.celllife.idart.client.part;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-06-16
 * Time: 18h18
 */
public abstract class RawMaterial extends Part {

    public RawMaterial() {
    }
}
