package org.celllife.idart.application.routeofadministration;

import org.celllife.idart.domain.routeofadministration.RouteOfAdministration;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface RouteOfAdministrationResourceService {

    RouteOfAdministration save(RouteOfAdministration routeOfAdministration);

    RouteOfAdministration findByCode(String code);

    Iterable<RouteOfAdministration> findAll();

}