package org.celllife.idart.application.clinicpractitioner

import org.celllife.idart.application.clinic.ClinicResourceService
import org.celllife.idart.application.practitioner.PractitionerProvider
import org.celllife.idart.application.practitioner.PractitionerResourceService
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.clinicpractitioner.ClinicPractitionerService
import org.celllife.idart.domain.facility.Facility
import org.celllife.idart.domain.practitioner.Practitioner
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class ClinicPractitionerApplicationServiceImpl implements ClinicPractitionerResourceService {

    static final String CLINIC_PRACTITIONER_IDENTIFIER_SYSTEM_TEMPLATE =
        "http://www.cell-life.org/idart/clinics/%s/practitioners"

    @Autowired ClinicResourceService clinicResourceService

    @Autowired PractitionerResourceService practitionerResourceService

    @Autowired ClinicPractitionerService clinicPractitionerService

    @Autowired PractitionerProvider prehmisPractitionerProvider

    /**
     * {@inheritDoc}
     */
    @Override
    void save(String clinicIdentifier, String practitionerIdentifier, Practitioner practitioner) {

        practitioner.addIdentifier(
                String.format(CLINIC_PRACTITIONER_IDENTIFIER_SYSTEM_TEMPLATE, clinicIdentifier),
                practitionerIdentifier
        )

        save(clinicIdentifier, practitioner)
    }

    /**
     * {@inheritDoc}
     */
    @Override
    void save(String clinicIdentifier, Practitioner practitioner) {

        def clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        save(clinic, practitioner)
    }

    /**
     * {@inheritDoc}
     */
    @Override
    Iterable<Practitioner> findPractitionersByClinicIdentifier(String clinicIdentifier) {

        Clinic clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        lookupFromExternalProvidersAndSave(clinic)

        clinicPractitionerService.findPractitionersByClinic(clinic)
    }

    /**
     * {@inheritDoc}
     */
    @Override
    Iterable<Practitioner> findPractitionersByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier,
                                                                                        String practitionerIdentifier) {

        clinicPractitionerService.findPractitionersByClinicIdentifierAndPractitionerIdentifier(clinicIdentifier,
                practitionerIdentifier)
    }

    /**
     * {@inheritDoc}
     */
    @Override
    Practitioner findOnePractitionerByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier,
                                                                                String practitionerIdentifier) {

        clinicPractitionerService.findOnePractitionerByClinicIdentifierAndPractitionerIdentifier(clinicIdentifier,
                practitionerIdentifier)
    }

    /**
     * Lookup practitioner from external providers and save
     *
     * @param clinic
     */
    void lookupFromExternalProvidersAndSave(Clinic clinic) {
        lookupFromExternalProviders(clinic).each { practitioner -> save(clinic, practitioner) }
    }

    /**
     * Lookup practitioner from external providers
     *
     * @param clinic
     * @return
     */
    Set<Practitioner> lookupFromExternalProviders(Clinic clinic) {

        Set<Practitioner> practitioners = []

        ((Facility) clinic).getIdentifierSystems().each { identifierSystem ->

            String clinicIdentifierValue = ((Facility) clinic).getIdentifierValue(identifierSystem)
            switch (identifierSystem) {
                case "http://prehmis.capetown.gov.za":
                    practitioners << prehmisPractitionerProvider.findAll(clinicIdentifierValue)
                    break
                default:
                    break
            }
        }

        practitioners.flatten()
    }

    /**
     * Save Practitioner and ClinicPractitioner relationship
     *
     * @param clinic
     * @param practitioner
     */
    void save(Clinic clinic, Practitioner practitioner) {

        practitioner = practitionerResourceService.save(practitioner)

        clinicPractitionerService.save(clinic, practitioner)

    }
}
