package org.celllife.idart.application.clinicpractitioner

import org.celllife.idart.domain.clinic.ClinicNotFoundException
import org.celllife.idart.application.clinic.ClinicResourceService
import org.celllife.idart.application.practitioner.PractitionerProvider
import org.celllife.idart.application.practitioner.PractitionerResourceService
import org.celllife.idart.domain.clinicpractitioner.ClinicPractitionerService
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.facility.Facility
import org.celllife.idart.domain.practitioner.Practitioner
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service    

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class ClinicPractitionerApplicationServiceImpl implements ClinicPractitionerResourceService {

    @Autowired ClinicResourceService clinicResourceService

    @Autowired PractitionerResourceService practitionerResourceService

    @Autowired ClinicPractitionerService clinicPractitionerService

    @Autowired PractitionerProvider prehmisPractitionerProvider

    @Override
    void save(String clinicIdentifier, String practitionerIdentifier, Practitioner practitioner) {

        practitioner.addIdentifier(
                String.format(
                        "http://www.cell-life.org/idart/clinics/%s/practitioners",
                        clinicIdentifier
                ),
                practitionerIdentifier
        )

        save(clinicIdentifier, practitioner)
    }

    @Override
    void save(String clinicIdentifier, Practitioner practitioner) {

        def clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        save(practitioner, clinic)
    }

    @Override
    Iterable<Practitioner> findPractitionersByClinicIdentifier(String clinicIdentifier) {

        Clinic clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        lookupAndSyncWithExternalProviders(clinic)
                .collect { practitioner -> practitionerResourceService.save(practitioner) }
                .collect { practitioner -> save(practitioner, clinic) }
    }

    @Override
    Iterable<Practitioner> findPractitionersByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier) {
        return null
    }

    @Override
    Practitioner findOnePractitionerByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier) {
        return null
    }

    Set<Practitioner> lookupAndSyncWithExternalProviders(Clinic clinic) {

        Set<Practitioner> practitioners = []

        ((Facility) clinic).getIdentifierSystems().each { identifierSystem ->

            String clinicIdentifierValue = ((Facility) clinic).getIdentifierValue(identifierSystem)
            switch (identifierSystem) {
                case "http://prehmis.capetown.gov.za":
                    practitioners << prehmisPractitionerProvider.findAll(clinicIdentifierValue)
                    break
                default:
                    break
            }
        }

        practitioners.flatten()
    }

    Practitioner save(Practitioner practitioner, Clinic clinic) {

        practitioner = practitionerResourceService.save(practitioner)

        clinicPractitionerService.save(clinic, practitioner)

        practitioner
    }
}
