package org.celllife.idart.domain.encounter

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface EncounterSequence {

    Long nextValue()

}