package org.celllife.idart.domain.encounter

import org.celllife.idart.domain.common.Identifier
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class EncounterServiceImpl implements EncounterService {

    @Autowired EncounterRepository encounterRepository

    @Override
    Encounter save(Encounter encounter) {

        Encounter existingEncounter = findByIdentifiers(encounter.identifiers)
        if (existingEncounter == null) {
            existingEncounter = encounter.class.newInstance()
        }

        existingEncounter.merge(encounter)

        encounterRepository.save(existingEncounter)
    }


    @Override
    Iterable<Encounter> findAll() {
        encounterRepository.findAll()
    }

    @Override
    Encounter findByIdentifier(String identifier) {
        null
    }

    @Override
    Encounter findByIdentifiers(Iterable<Identifier> identifiers) {

        if (identifiers == null) {
            return null
        }

        for (Identifier identifier: identifiers) {
            Encounter encounter = encounterRepository.findOneByIdentifier(identifier.system, identifier.value)
            if (encounter != null) {
                return encounter
            }
        }

        null
    }
}