package org.celllife.idart.domain.system

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface SystemValidator {

    void validate(System system) throws SystemValidationException

}