package org.celllife.idart.domain.system

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SystemService {

    Iterable<System> save(Iterable<System> systems)

    System save(System system)

    Iterable<System> findAll()

    System findByIdentifier(String identifier)

}