package org.celllife.idart.domain.system

import org.celllife.idart.domain.party.Party

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class System extends Party {

    String identifier

}