package org.celllife.idart.domain.system;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SystemRepository {

    System save(System system)

    public <S extends System> Iterable<S> save(Iterable<S> systems)

    System findOne(Long pk)

    Iterable<System> findAll()

    System findOneByIdentifier(String identifier);

}
