package org.celllife.idart.infrastructure.validation.product

import org.celllife.idart.domain.product.Good
import org.celllife.idart.domain.product.GoodValidationException
import org.celllife.idart.domain.product.GoodValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateGoodValidator implements GoodValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(Good good) throws GoodValidationException {

        Set<ConstraintViolation<Good>> constraintViolations = validatorFactory.validator.validate(good)

        if (!constraintViolations.empty) {
            throw new GoodValidationException(constraintViolations)
        }
    }
}
