package org.celllife.idart.application.encounter

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class EncounterApplicationServiceMixin {

}