package org.celllife.idart.domain.clinicprescription

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.prescription.Prescription

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface ClinicPrescriptionService {

    boolean exists(Clinic clinic, Prescription prescription, Date dateActive)

    void save(Clinic clinic, Prescription prescription)

    void save(Clinic clinic, Iterable<Prescription> prescriptions)

    void save(Prescription prescription, Iterable<Clinic> clinics)

    void deleteByClinic(Clinic clinic)

    void deleteByPrescription(Prescription prescription)

    void delete(Clinic clinic, Prescription prescription)

    Iterable<Prescription> findPrescriptionsByClinic(Clinic clinic)

    Iterable<Prescription> findPrescriptionsByClinicIdentifier(String clinicIdentifier)

    Iterable<Prescription> findPrescriptionsByClinicIdentifierAndPrescriptionIdentifier(String clinicIdentifier, String prescriptionIdentifier)

    Prescription findOnePrescriptionByClinicIdentifierAndPrescriptionIdentifier(String clinicIdentifier, String prescriptionIdentifier)

    Iterable<Clinic> findClinicsByPrescription(Prescription prescription)
}
