package org.celllife.idart.domain.clinicprescription;
                              
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.prescription.Prescription

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicPrescriptionRepository {

    ClinicPrescription save(ClinicPrescription clinicPrescription)

    ClinicPrescription findByClinicAndPrescriptionAndDateActive(Clinic clinic, Prescription prescription, Date dateActive)

    Long countByClinicAndPrescriptionAndDateActive(Clinic clinic, Prescription prescription, Date dateActive)

    Iterable<ClinicPrescription> findByClinicAndDateActive(Clinic clinic, Date dateActive)

    Iterable<ClinicPrescription> findByClinicIdentifierAndDateActive(String clinicIdentifier, Date dateActive)

    Iterable<ClinicPrescription> findByClinicIdentifierAndPrescriptionIdentifierAndDateActive(String clinicIdentifier, String prescriptionIdentifier, Date dateActive)

    ClinicPrescription findOneByClinicIdentifierAndPrescriptionIdentifierAndDateActive(String clinicIdentifier, String prescriptionIdentifier, Date dateActive)

    Iterable<ClinicPrescription> findByPrescriptionAndDateActive(Prescription prescription, Date dateActive)

}
