package org.celllife.idart.domain.clinicprescription

import org.celllife.idart.domain.common.Persistable
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.prescription.Prescription

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class ClinicPrescription implements Persistable<Long> {

    Long pk

    Clinic clinic

    Prescription prescription

    Date fromDate

    Date thruDate

}
