package org.celllife.idart.application.person;

import org.celllife.idart.domain.person.Person;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface PersonResourceService {

    Person save(Person person);

    Person findByIdentifier(String identifier);

    Iterable<Person> findAll();

}