package org.celllife.idart.application.person;

import org.celllife.idart.domain.person.Person;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
public interface PersonApplicationService {

    Person update(Person person, Long existingPersonPk);

}