package org.celllife.idart.infrastructure.counter.druggroup

import org.celllife.idart.domain.counter.CounterService
import org.celllife.idart.domain.druggroup.DrugGroupSequence
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class CounterDrugGroupSequence implements DrugGroupSequence {

    static final String CODE_COUNTER_NAME = "DrugGroupCode"

    @Autowired CounterService counterService

    @Override
    Long nextValue() {
        counterService.getNextValue(CODE_COUNTER_NAME)
    }
}
