package org.celllife.idart.domain.patient

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class PatientValidationException extends RuntimeException {

    Set<ConstraintViolation<Patient>> constraintViolations

    PatientValidationException(Set<ConstraintViolation<Patient>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
