package org.celllife.idart.domain.patient

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface PatientValidator {

    void validate(Patient patient) throws PatientValidationException

}