package org.celllife.idart.domain.practitioner

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface PractitionerSequence {

    Long nextValue()

}