package org.celllife.idart.domain.dispensedmedication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface DispensedMedicationSequence {

    Long nextValue()

}