package org.celllife.idart.domain.dispensedmedication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface DispensedMedicationValidator {

    void validate(DispensedMedication dispensedMedication) throws DispensedMedicationValidationException

}