package org.celllife.idart.application.clinicmedication;

import org.celllife.idart.domain.clinic.Clinic;
import org.celllife.idart.domain.medication.Medication;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicMedicationResourceService {

    void save(String clinicIdentifier, String medicationIdentifier, Medication medication);

    void save(String clinicIdentifier, Medication medication);

    Iterable<Medication> findMedicationsByClinicIdentifier(String clinicIdentifier);

    Iterable<Medication> findMedicationsByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier);

    Medication findOneMedicationByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier);
}
