package org.celllife.idart.infrastructure.springdata.system;

import org.celllife.idart.domain.system.System;
import org.celllife.idart.domain.system.SystemRepository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.repository.annotation.RestResource;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@RestResource(path = "systems")
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SpringDataSystemRepository extends PagingAndSortingRepository<System, Long>, SystemRepository {

    @Query("select system " +
            "from System system " +
            "where system.identifier = :identifier")
    System findOneByIdentifier(@Param("identifier") String identifier);

}
