package org.celllife.idart.infrastructure.validation.administrationmethod

import org.celllife.idart.domain.administrationmethod.AdministrationMethod
import org.celllife.idart.domain.administrationmethod.AdministrationMethodValidationException
import org.celllife.idart.domain.administrationmethod.AdministrationMethodValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateAdministrationMethodValidator implements AdministrationMethodValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(AdministrationMethod administrationMethod) throws AdministrationMethodValidationException {

        Set<ConstraintViolation<AdministrationMethod>> constraintViolations = validatorFactory.validator.validate(administrationMethod)

        if (!constraintViolations.empty) {
            throw new AdministrationMethodValidationException(constraintViolations)
        }
    }
}
