package org.celllife.idart.application.user;

import org.celllife.idart.domain.user.User;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UserResourceService {

    User save(User user);

    User findByUsername(String username);

    Iterable<User> findAll();

}