package org.celllife.idart.domain.clinic

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface ClinicSequence {

    Long nextValue()

}