package org.celllife.idart.application.clinicprescription;

import org.celllife.idart.domain.prescription.Prescription;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
public interface ClinicPrescriptionResourceService {

    void save(String clinicIdentifier, String prescriptionIdentifier, Prescription prescription);

}
