package org.celllife.idart.domain.prescription

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface PrescriptionSequence {

    Long nextValue()

}