package org.celllife.idart.application.clinicpractitioner;

import org.celllife.idart.domain.clinic.Clinic;
import org.celllife.idart.domain.practitioner.Practitioner;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicPractitionerResourceService {

    void save(String clinicIdentifier, String practitionerIdentifier, Practitioner practitioner);

    void save(String clinicIdentifier, Practitioner practitioner);

    Iterable<Practitioner> findPractitionersByClinicIdentifier(String clinicIdentifier);

    Iterable<Practitioner> findPractitionersByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier);

    Practitioner findOnePractitionerByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier);
}
