package org.celllife.idart.application.medication

import org.celllife.idart.domain.medication.Medication
import org.celllife.idart.domain.medication.MedicationService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service
@Mixin(MedicationApplicationServiceMixin)
@Generated("org.celllife.idart.codegen.CodeGenerator")
class MedicationApplicationServiceImpl implements MedicationApplicationService, MedicationResourceService {

    @Autowired MedicationService medicationService

    Medication save(Medication medication) {
        medicationService.save(medication)
    }

    Medication findByIdentifier(String identifier) {
        medicationService.findByIdentifier(identifier)
    }

    Iterable<Medication> findAll() {
        medicationService.findAll()
    }

}