package org.celllife.idart.domain.clinicpatient

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.patient.Patient

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class ClinicPatient {

    Long pk

    Clinic clinic

    Patient patient

    Date fromDate

    Date thruDate

}
