package org.celllife.idart.domain.clinicpatient

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.patient.Patient

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface ClinicPatientService {

    boolean exists(Clinic clinic, Patient patient, Date dateActive)

    void save(Clinic clinic, Patient patient)

    void save(Clinic clinic, Iterable<Patient> patients)

    void save(Patient patient, Iterable<Clinic> clinics)

    void deleteByClinic(Clinic clinic)

    void deleteByPatient(Patient patient)

    void delete(Clinic clinic, Patient patient)

    Iterable<Patient> findPatientsByClinic(Clinic clinic)

    Iterable<Patient> findPatientsByClinicIdentifier(String clinicIdentifier)

    Iterable<Patient> findPatientsByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier)

    Patient findOnePatientByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier)

    Iterable<Clinic> findClinicsByPatient(Patient patient)
}
