package org.celllife.idart.domain.clinicpatient;
                              
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.patient.Patient

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicPatientRepository {

    ClinicPatient save(ClinicPatient clinicPatient)

    ClinicPatient findByClinicAndPatientAndDateActive(Clinic clinic, Patient patient, Date dateActive)

    Long countByClinicAndPatientAndDateActive(Clinic clinic, Patient patient, Date dateActive)

    Iterable<ClinicPatient> findByClinicAndDateActive(Clinic clinic, Date dateActive)

    Iterable<ClinicPatient> findByClinicIdentifierAndDateActive(String clinicIdentifier, Date dateActive)

    Iterable<ClinicPatient> findByClinicIdentifierAndPatientIdentifierAndDateActive(String clinicIdentifier, String patientIdentifier, Date dateActive)

    ClinicPatient findOneByClinicIdentifierAndPatientIdentifierAndDateActive(String clinicIdentifier, String patientIdentifier, Date dateActive)

    Iterable<ClinicPatient> findByPatientAndDateActive(Patient patient, Date dateActive)

}
