package org.celllife.idart.application.druggroup;

import org.celllife.idart.domain.druggroup.DrugGroup;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface DrugGroupResourceService {

    DrugGroup save(DrugGroup drugGroup);

    DrugGroup findByIdentifier(String identifier);

    Iterable<DrugGroup> findAll();

}