package org.celllife.idart.domain.medication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface MedicationValidator {

    void validate(Medication medication) throws MedicationValidationException

}