package org.celllife.idart.domain.medication

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class MedicationValidationException extends RuntimeException {

    Set<ConstraintViolation<Medication>> constraintViolations

    MedicationValidationException(Set<ConstraintViolation<Medication>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
