package org.celllife.idart.application.clinicprescription

import org.celllife.idart.application.clinic.ClinicResourceService
import org.celllife.idart.application.prescription.PrescriptionResourceService
import org.celllife.idart.domain.clinicprescription.ClinicPrescriptionService
import org.celllife.idart.domain.prescription.Prescription
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class ClinicPrescriptionApplicationServiceImpl implements ClinicPrescriptionResourceService {

    @Autowired ClinicResourceService clinicResourceService

    @Autowired PrescriptionResourceService prescriptionResourceService

    @Autowired ClinicPrescriptionService clinicPrescriptionService

    @Override
    void save(String clinicIdentifier, String prescriptionIdentifier, Prescription prescription) {

        prescription.addIdentifier(
                String.format(
                        "http://www.cell-life.org/idart/clinics/%s/prescriptions",
                        clinicIdentifier
                ),
                prescriptionIdentifier
        )

        prescription = prescriptionResourceService.save(prescription)

        def clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        clinicPrescriptionService.save(clinic, prescription)
    }
}
