package org.celllife.idart.domain.drug

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class DrugValidationException extends RuntimeException {

    Set<ConstraintViolation<Drug>> constraintViolations

    DrugValidationException(Set<ConstraintViolation<Drug>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
