package org.celllife.idart.domain.drug

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface DrugValidator {

    void validate(Drug drug) throws DrugValidationException

}