package org.celllife.idart.domain.product

import org.celllife.idart.domain.common.Identifier

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface GoodService {

    Good save(Good good)

    Iterable<Good> findAll()

    Good findByIdentifier(String identifier)

    Good findByIdentifiers(Iterable<Identifier> identifiers)

}