package org.celllife.idart.domain.product

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface GoodSequence {

    Long nextValue()

}