package org.celllife.idart.domain.product

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class GoodValidationException extends RuntimeException {

    Set<ConstraintViolation<Good>> constraintViolations

    GoodValidationException(Set<ConstraintViolation<Good>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
