package org.celllife.idart.domain.prescribedmedication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface PrescribedMedicationSequence {

    Long nextValue()

}