package org.celllife.idart.domain.clinicdispensation

import org.celllife.idart.domain.common.Persistable
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.dispensation.Dispensation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class ClinicDispensation implements Persistable<Long> {

    Long pk

    Clinic clinic

    Dispensation dispensation

    Date fromDate

    Date thruDate

}
