package org.celllife.idart.domain.clinicdispensation;
                              
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.dispensation.Dispensation

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicDispensationRepository {

    ClinicDispensation save(ClinicDispensation clinicDispensation)

    ClinicDispensation findByClinicAndDispensationAndDateActive(Clinic clinic, Dispensation dispensation, Date dateActive)

    Long countByClinicAndDispensationAndDateActive(Clinic clinic, Dispensation dispensation, Date dateActive)

    Iterable<ClinicDispensation> findByClinicAndDateActive(Clinic clinic, Date dateActive)

    Iterable<ClinicDispensation> findByClinicIdentifierAndDateActive(String clinicIdentifier, Date dateActive)

    Iterable<ClinicDispensation> findByClinicIdentifierAndDispensationIdentifierAndDateActive(String clinicIdentifier, String dispensationIdentifier, Date dateActive)

    ClinicDispensation findOneByClinicIdentifierAndDispensationIdentifierAndDateActive(String clinicIdentifier, String dispensationIdentifier, Date dateActive)

    Iterable<ClinicDispensation> findByDispensationAndDateActive(Dispensation dispensation, Date dateActive)

}
