package org.celllife.idart.infrastructure.validation.part

import org.celllife.idart.domain.part.Subassembly
import org.celllife.idart.domain.part.SubassemblyValidationException
import org.celllife.idart.domain.part.SubassemblyValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateSubassemblyValidator implements SubassemblyValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(Subassembly subassembly) throws SubassemblyValidationException {

        Set<ConstraintViolation<Subassembly>> constraintViolations = validatorFactory.validator.validate(subassembly)

        if (!constraintViolations.empty) {
            throw new SubassemblyValidationException(constraintViolations)
        }
    }
}
