package org.celllife.idart.infrastructure.validation.part

import org.celllife.idart.domain.part.Compound
import org.celllife.idart.domain.part.CompoundValidationException
import org.celllife.idart.domain.part.CompoundValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateCompoundValidator implements CompoundValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(Compound compound) throws CompoundValidationException {

        Set<ConstraintViolation<Compound>> constraintViolations = validatorFactory.validator.validate(compound)

        if (!constraintViolations.empty) {
            throw new CompoundValidationException(constraintViolations)
        }
    }
}
