package org.celllife.idart.infrastructure.validation.part

import org.celllife.idart.domain.part.FinishedGood
import org.celllife.idart.domain.part.FinishedGoodValidationException
import org.celllife.idart.domain.part.FinishedGoodValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateFinishedGoodValidator implements FinishedGoodValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(FinishedGood finishedGood) throws FinishedGoodValidationException {

        Set<ConstraintViolation<FinishedGood>> constraintViolations = validatorFactory.validator.validate(finishedGood)

        if (!constraintViolations.empty) {
            throw new FinishedGoodValidationException(constraintViolations)
        }
    }
}
