package org.celllife.idart.infrastructure.validation.part

import org.celllife.idart.domain.part.RawMaterial
import org.celllife.idart.domain.part.RawMaterialValidationException
import org.celllife.idart.domain.part.RawMaterialValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateRawMaterialValidator implements RawMaterialValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(RawMaterial rawMaterial) throws RawMaterialValidationException {

        Set<ConstraintViolation<RawMaterial>> constraintViolations = validatorFactory.validator.validate(rawMaterial)

        if (!constraintViolations.empty) {
            throw new RawMaterialValidationException(constraintViolations)
        }
    }
}
