package org.celllife.idart.infrastructure.validation.part

import org.celllife.idart.domain.part.Drug
import org.celllife.idart.domain.part.DrugValidationException
import org.celllife.idart.domain.part.DrugValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateDrugValidator implements DrugValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(Drug drug) throws DrugValidationException {

        Set<ConstraintViolation<Drug>> constraintViolations = validatorFactory.validator.validate(drug)

        if (!constraintViolations.empty) {
            throw new DrugValidationException(constraintViolations)
        }
    }
}
