package org.celllife.idart.domain.user;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UserRepository {

    User save(User user)

    public <S extends User> Iterable<S> save(Iterable<S> users)

    User findOne(Long pk)

    Iterable<User> findAll()

    User findOneByUsername(String username);

}
