package org.celllife.idart.domain.user

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UserService {

    Iterable<User> save(Iterable<User> users)

    User save(User user)

    Iterable<User> findAll()

    User findByUsername(String username)

}