package org.celllife.idart.domain.user

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface UserValidator {

    void validate(User user) throws UserValidationException

}