package org.celllife.idart.domain.user

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class UserServiceImpl implements UserService {

    @Autowired UserRepository userRepository

    @Override
    Iterable<User> save(Iterable<User> users) {
        userRepository.save(users)
    }

    @Override
    User save(User user) {
        userRepository.save(user)
    }

    @Override
    Iterable<User> findAll() {
        userRepository.findAll()
    }

    @Override
    User findByUsername(String username) {
        userRepository.findOneByUsername(username)
    }
}