package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface CompoundService {

    Compound save(Compound compound)

    Iterable<Compound> findAll()

    Compound findByIdentifier(String identifier)

    Compound findByIdentifiers(Iterable<Identifier> identifiers)

}