package org.celllife.idart.domain.part

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class DrugGroupValidationException extends RuntimeException {

    Set<ConstraintViolation<DrugGroup>> constraintViolations

    DrugGroupValidationException(Set<ConstraintViolation<DrugGroup>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
