package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class FinishedGoodServiceImpl implements FinishedGoodService {

    @Autowired FinishedGoodRepository finishedGoodRepository

    @Override
    FinishedGood findByIdentifiers(Iterable<Identifier> identifiers) {
        for (identifier in identifiers) {
            def existingFinishedGood = finishedGoodRepository.findOneByIdentifier(identifier.system, identifier.value)
            if (existingFinishedGood != null) {
                return existingFinishedGood
            }
        }

        null
    }
}
