package org.celllife.idart.domain.part

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class FinishedGoodValidationException extends RuntimeException {

    Set<ConstraintViolation<FinishedGood>> constraintViolations

    FinishedGoodValidationException(Set<ConstraintViolation<FinishedGood>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
