package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface PartService {

    Part save(Part part)

    Iterable<Part> findAll()

    Part findByIdentifier(String identifier)

    Part findByIdentifiers(Iterable<Identifier> identifiers)

}