package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class PartServiceImpl implements PartService {

    @Autowired PartRepository partRepository

    @Override
    Part save(Part part) {

        Part existingPart = findByIdentifiers(part.identifiers)
        if (existingPart == null) {
            existingPart = part.class.newInstance()
        }

        existingPart.merge(part)

        partRepository.save(existingPart)
    }


    @Override
    Iterable<Part> findAll() {
        partRepository.findAll()
    }

    @Override
    Part findByIdentifier(String identifier) {
        null
    }

    @Override
    Part findByIdentifiers(Iterable<Identifier> identifiers) {

        if (identifiers == null) {
            return null
        }

        for (Identifier identifier: identifiers) {
            Part part = partRepository.findOneByIdentifier(identifier.system, identifier.value)
            if (part != null) {
                return part
            }
        }

        null
    }
}