package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Service class RawMaterialServiceImpl implements RawMaterialService {

    @Autowired RawMaterialRepository rawMaterialRepository

    @Override
    RawMaterial findByIdentifiers(Iterable<Identifier> identifiers) {
        for (identifier in identifiers) {
            def existingRawMaterial = rawMaterialRepository.findOneByIdentifier(identifier.system, identifier.value)
            if (existingRawMaterial != null) {
                return existingRawMaterial
            }
        }

        null
    }

}
