package org.celllife.idart.domain.part

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class RawMaterialValidationException extends RuntimeException {

    Set<ConstraintViolation<RawMaterial>> constraintViolations

    RawMaterialValidationException(Set<ConstraintViolation<RawMaterial>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
