package org.celllife.idart.domain.part

import org.celllife.idart.domain.common.Identifier

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SubassemblyService {

    Subassembly save(Subassembly subassembly)

    Iterable<Subassembly> findAll()

    Subassembly findByIdentifier(String identifier)

    Subassembly findByIdentifiers(Iterable<Identifier> identifiers)

}