package org.celllife.idart.application.user

import org.celllife.idart.domain.user.User
import org.celllife.idart.domain.user.UserService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class UserApplicationServiceImpl implements UserApplicationService, UserResourceService {

    @Autowired UserService userService

    User save(User user) {
        userService.save(user)
    }

    User findByUsername(String username) {
        userService.findByUsername(username)
    }

    Iterable<User> findAll() {
        userService.findAll()
    }

}