package org.celllife.idart.application.clinicpatient;

import org.celllife.idart.domain.clinic.Clinic;
import org.celllife.idart.domain.patient.Patient;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicPatientResourceService {

    void save(String clinicIdentifier, String patientIdentifier, Patient patient);

    void save(String clinicIdentifier, Patient patient);

    Iterable<Patient> findPatientsByClinicIdentifier(String clinicIdentifier);

    Iterable<Patient> findPatientsByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier);

    Patient findOnePatientByClinicIdentifierAndPatientIdentifier(String clinicIdentifier, String patientIdentifier);
}
