package org.celllife.idart.domain.compound

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface CompoundSequence {

    Long nextValue()

}