package org.celllife.idart.infrastructure.validation.druggroup

import org.celllife.idart.domain.druggroup.DrugGroup
import org.celllife.idart.domain.druggroup.DrugGroupValidationException
import org.celllife.idart.domain.druggroup.DrugGroupValidator
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component

import javax.validation.ConstraintViolation
import javax.validation.ValidatorFactory

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Component class HibernateDrugGroupValidator implements DrugGroupValidator {

    @Autowired ValidatorFactory validatorFactory

    @Override
    void validate(DrugGroup drugGroup) throws DrugGroupValidationException {

        Set<ConstraintViolation<DrugGroup>> constraintViolations = validatorFactory.validator.validate(drugGroup)

        if (!constraintViolations.empty) {
            throw new DrugGroupValidationException(constraintViolations)
        }
    }
}
