package org.celllife.idart.domain.clinicpractitioner

import org.celllife.idart.domain.common.Persistable
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.practitioner.Practitioner

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class ClinicPractitioner implements Persistable<Long> {

    Long pk

    Clinic clinic

    Practitioner practitioner

    Date fromDate

    Date thruDate

}
