package org.celllife.idart.domain.clinicpractitioner

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.practitioner.Practitioner

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface ClinicPractitionerService {

    boolean exists(Clinic clinic, Practitioner practitioner, Date dateActive)

    void save(Clinic clinic, Practitioner practitioner)

    void save(Clinic clinic, Iterable<Practitioner> practitioners)

    void save(Practitioner practitioner, Iterable<Clinic> clinics)

    void deleteByClinic(Clinic clinic)

    void deleteByPractitioner(Practitioner practitioner)

    void delete(Clinic clinic, Practitioner practitioner)

    Iterable<Practitioner> findPractitionersByClinic(Clinic clinic)

    Iterable<Practitioner> findPractitionersByClinicIdentifier(String clinicIdentifier)

    Iterable<Practitioner> findPractitionersByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier)

    Practitioner findOnePractitionerByClinicIdentifierAndPractitionerIdentifier(String clinicIdentifier, String practitionerIdentifier)

    Iterable<Clinic> findClinicsByPractitioner(Practitioner practitioner)
}
