package org.celllife.idart.domain.clinicpractitioner;
                              
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.practitioner.Practitioner

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicPractitionerRepository {

    ClinicPractitioner save(ClinicPractitioner clinicPractitioner)

    ClinicPractitioner findByClinicAndPractitionerAndDateActive(Clinic clinic, Practitioner practitioner, Date dateActive)

    Long countByClinicAndPractitionerAndDateActive(Clinic clinic, Practitioner practitioner, Date dateActive)

    Iterable<ClinicPractitioner> findByClinicAndDateActive(Clinic clinic, Date dateActive)

    Iterable<ClinicPractitioner> findByClinicIdentifierAndDateActive(String clinicIdentifier, Date dateActive)

    Iterable<ClinicPractitioner> findByClinicIdentifierAndPractitionerIdentifierAndDateActive(String clinicIdentifier, String practitionerIdentifier, Date dateActive)

    ClinicPractitioner findOneByClinicIdentifierAndPractitionerIdentifierAndDateActive(String clinicIdentifier, String practitionerIdentifier, Date dateActive)

    Iterable<ClinicPractitioner> findByPractitionerAndDateActive(Practitioner practitioner, Date dateActive)

}
