package org.celllife.idart.application.organisation

import org.celllife.idart.domain.common.Identifier
import org.celllife.idart.domain.organisation.LegalOrganisation
import org.celllife.idart.domain.organisation.LegalOrganisationService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class LegalOrganisationApplicationServiceMixin {

}