package org.celllife.idart.client.common;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @generated by org.celllife.idart.codegen.CodeGenerator
 * Date: 2013-07-18
 * Time: 18h28
 */
public final class Quantity implements Serializable {

    public BigDecimal value;

    public Coded unitOfMeasure;

}
