package org.celllife.idart.domain.clinicmedication

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.medication.Medication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface ClinicMedicationService {

    boolean exists(Clinic clinic, Medication medication, Date dateActive)

    void save(Clinic clinic, Medication medication)

    void save(Clinic clinic, Iterable<Medication> medications)

    void save(Medication medication, Iterable<Clinic> clinics)

    void deleteByClinic(Clinic clinic)

    void deleteByMedication(Medication medication)

    void delete(Clinic clinic, Medication medication)

    Iterable<Medication> findMedicationsByClinic(Clinic clinic)

    Iterable<Medication> findMedicationsByClinicIdentifier(String clinicIdentifier)

    Iterable<Medication> findMedicationsByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier)

    Medication findOneMedicationByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier)

    Iterable<Clinic> findClinicsByMedication(Medication medication)
}
