package org.celllife.idart.domain.clinicmedication;
                              
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.medication.Medication

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface ClinicMedicationRepository {

    ClinicMedication save(ClinicMedication clinicMedication)

    ClinicMedication findByClinicAndMedicationAndDateActive(Clinic clinic, Medication medication, Date dateActive)

    Long countByClinicAndMedicationAndDateActive(Clinic clinic, Medication medication, Date dateActive)

    Iterable<ClinicMedication> findByClinicAndDateActive(Clinic clinic, Date dateActive)

    Iterable<ClinicMedication> findByClinicIdentifierAndDateActive(String clinicIdentifier, Date dateActive)

    Iterable<ClinicMedication> findByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier)

    ClinicMedication findOneByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier)

    Iterable<ClinicMedication> findByMedicationAndDateActive(Medication medication, Date dateActive)

}
