package org.celllife.idart.domain.clinicmedication

import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.medication.Medication

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class ClinicMedication {

    Long pk

    Clinic clinic

    Medication medication

    Date fromDate

    Date thruDate

}
