package org.celllife.idart.infrastructure.springdata.user;

import org.celllife.idart.domain.user.User;
import org.celllife.idart.domain.user.UserRepository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.repository.annotation.RestResource;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@RestResource(path = "users")
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface SpringDataUserRepository extends PagingAndSortingRepository<User, Long>, UserRepository {

    @Query("select user " +
            "from User user " +
            "where user.username = :username")
    User findOneByUsername(@Param("username") String username);

}
