package org.celllife.idart.domain.routeofadministration

import javax.validation.ConstraintViolation

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
class RouteOfAdministrationValidationException extends RuntimeException {

    Set<ConstraintViolation<RouteOfAdministration>> constraintViolations

    RouteOfAdministrationValidationException(Set<ConstraintViolation<RouteOfAdministration>> constraintViolations) {
        this.constraintViolations = constraintViolations
    }
}
