package org.celllife.idart.domain.routeofadministration;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface RouteOfAdministrationRepository {

    RouteOfAdministration save(RouteOfAdministration routeOfAdministration)

    public <S extends RouteOfAdministration> Iterable<S> save(Iterable<S> routesOfAdministration)

    RouteOfAdministration findOne(Long pk)

    Iterable<RouteOfAdministration> findAll()

    RouteOfAdministration findOneByCode(String system, String code);

}
