package org.celllife.idart.domain.routeofadministration

import org.celllife.idart.domain.common.Code

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface RouteOfAdministrationService {

    Iterable<RouteOfAdministration> save(Iterable<RouteOfAdministration> routesOfAdministration)

    RouteOfAdministration save(RouteOfAdministration routeOfAdministration)

    Iterable<RouteOfAdministration> findAll()

    RouteOfAdministration findByCode(String code)

    RouteOfAdministration findByCodes(Iterable<Code> codes)

}