package org.celllife.idart.domain.routeofadministration

import org.celllife.idart.domain.common.Code

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class RouteOfAdministrationServiceImpl implements RouteOfAdministrationService {

    @Autowired RouteOfAdministrationRepository routeOfAdministrationRepository

    @Override
    Iterable<RouteOfAdministration> save(Iterable<RouteOfAdministration> routesOfAdministration) {
        routesOfAdministration.collect { routeOfAdministration -> (save(routeOfAdministration)) }
    }

    @Override
    RouteOfAdministration save(RouteOfAdministration routeOfAdministration) {
        routeOfAdministrationRepository.save(lookupAndMerge(routeOfAdministration))
    }

    RouteOfAdministration lookupAndMerge(RouteOfAdministration routeOfAdministration) {

        Code code = getLookupCode(routeOfAdministration)

        RouteOfAdministration existingRouteOfAdministration = routeOfAdministrationRepository.findOneByCode(code.system, code.value)

        if (existingRouteOfAdministration == null) {

            // Ensure that idartCodeValue is always set
            if (routeOfAdministration.idartCodeValue == null) {
                routeOfAdministration.addCode(RouteOfAdministration.IDART_SYSTEM, routeOfAdministration.defaultCodeValue)
            }

            return routeOfAdministration
        }

        existingRouteOfAdministration.mergeCodes(routeOfAdministration)
        existingRouteOfAdministration
    }

    static Code getLookupCode(RouteOfAdministration routeOfAdministration) {

        if (routeOfAdministration.idartCodeValue == null && routeOfAdministration.defaultCodeValue == null) {
            throw new RuntimeException("No code for default system [${ RouteOfAdministration.DEFAULT_SYSTEM}] or idart system [${ RouteOfAdministration.IDART_SYSTEM}]")
        }

        if (routeOfAdministration.defaultCodeValue != null) {
            return new Code(system: RouteOfAdministration.DEFAULT_SYSTEM, value: routeOfAdministration.defaultCodeValue)
        }

        return new Code(system: RouteOfAdministration.IDART_SYSTEM, value: routeOfAdministration.idartCodeValue)
    }

    @Override
    Iterable<RouteOfAdministration> findAll() {
        routeOfAdministrationRepository.findAll()
    }

    @Override
    RouteOfAdministration findByCode(String code) {
        routeOfAdministrationRepository.findOneByCode(RouteOfAdministration.IDART_SYSTEM, code)
    }

    @Override
    RouteOfAdministration findByCodes(Iterable<Code> codes) {

        if (codes == null) {
            return null
        }

        for (code in codes) {
            def routeOfAdministration = routeOfAdministrationRepository.findOneByCode(code.system, code.value)
            if (routeOfAdministration != null) {
                return routeOfAdministration
            }
        }

        null
    }
}