package org.celllife.idart.domain.routeofadministration

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
interface RouteOfAdministrationValidator {

    void validate(RouteOfAdministration routeOfAdministration) throws RouteOfAdministrationValidationException

}