package org.celllife.idart.application.unitofmeasure;

import org.celllife.idart.domain.unitofmeasure.UnitOfMeasure;

import javax.annotation.Generated;

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
public interface UnitOfMeasureResourceService {

    UnitOfMeasure save(UnitOfMeasure unitOfMeasure);

    UnitOfMeasure findByCode(String code);

    Iterable<UnitOfMeasure> findAll();

}