package org.celllife.idart.application.clinicmedication

import org.celllife.idart.application.clinic.ClinicResourceService
import org.celllife.idart.application.medication.MedicationResourceService
import org.celllife.idart.domain.clinicmedication.ClinicMedicationService
import org.celllife.idart.domain.clinic.Clinic
import org.celllife.idart.domain.medication.Medication
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service    

import javax.annotation.Generated

/**
 * Generated by org.celllife.idart.codegen.CodeGenerator
 */
@Generated("org.celllife.idart.codegen.CodeGenerator")
@Service class ClinicMedicationApplicationServiceImpl implements ClinicMedicationResourceService {

    @Autowired ClinicResourceService clinicResourceService

    @Autowired MedicationResourceService medicationResourceService

    @Autowired ClinicMedicationService clinicMedicationService

    @Override
    void save(String clinicIdentifier, String medicationIdentifier, Medication medication) {

        medication.addIdentifier(
                String.format(
                        "http://www.cell-life.org/idart/clinics/%s/medications",
                        clinicIdentifier
                ),
                medicationIdentifier
        )

        save(clinicIdentifier, medication)
    }

    @Override
    void save(String clinicIdentifier, Medication medication) {

        def clinic = clinicResourceService.findByIdentifier(clinicIdentifier)

        medication = medicationResourceService.save(medication)

        clinicMedicationService.save(clinic, medication)
    }

    @Override
    Iterable<Medication> findMedicationsByClinicIdentifier(String clinicIdentifier) {
         clinicMedicationService.findMedicationsByClinicIdentifier(clinicIdentifier)
    }

    @Override
    Iterable<Medication> findMedicationsByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier) {

    }

    @Override
    Medication findOneMedicationByClinicIdentifierAndMedicationIdentifier(String clinicIdentifier, String medicationIdentifier) {

    }
}
